theme: minima
title: Rsprague81's Blog
author: Rsprague81
email: peacefrog921@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn with me as I explore Github,  Git and learn how to code 

# social links
twitter_username: RACameronSprag2 # DO NOT include the @ character, or else the build will fail!
github_username:  Rsprague81 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
